### Imports

In [79]:
import os
import cv2
import numpy as np
import matplotlib.pyplot as plt
import requests

### Load images from GitHub

In [80]:
def get_filename(image_id):
  return f"in{image_id:06d}.jpg"

def get_ground_truth_filename(image_id):
  return f"gt{image_id:06d}.png"

In [81]:
def load_images(url, output_folder):
  images = []

  os.makedirs(output_folder, exist_ok=True)

  for i in range(1, 1100):
      fileName = get_filename(i)

      full_path = os.path.join(output_folder, fileName)

      if not os.path.exists(full_path):
        r = requests.get(url + fileName, allow_redirects=True)
        open(full_path, "wb").write(r.content)

      img = cv2.imread(full_path, cv2.IMREAD_GRAYSCALE)
      images.append(img)

  print("Loaded", len(images), "images")
  return images

In [82]:
def load_ground_truth(url, output_folder):
  ground_truth = []

  os.makedirs(output_folder, exist_ok=True)

  for i in range(1, 1100):
      fileName = get_ground_truth_filename(i)

      full_path = os.path.join(output_folder, fileName)

      if not os.path.exists(full_path):
        r = requests.get(url + fileName, allow_redirects=True)
        open(full_path, "wb").write(r.content)

      img = cv2.imread(full_path, cv2.IMREAD_GRAYSCALE)
      ground_truth.append(img)

  print("Loaded", len(ground_truth), "images")
  return ground_truth

In [83]:
url_pedestrian = "https://raw.githubusercontent.com/vision-agh/zaw_avs_materials/main/lab02_cfd/pedestrian/input/"
url_highway = "https://raw.githubusercontent.com/vision-agh/zaw_avs_materials/main/lab02_cfd/highway/input/"
url_office = "https://raw.githubusercontent.com/vision-agh/zaw_avs_materials/main/lab02_cfd/office/input/"

img_pedestrian = load_images(url_pedestrian, "pedestrian")
img_highway = load_images(url_highway, "highway")
img_office = load_images(url_office, "office")

Loaded 1099 images
Loaded 1099 images
Loaded 1099 images


In [84]:
url_pedestrian = "https://raw.githubusercontent.com/vision-agh/zaw_avs_materials/main/lab02_cfd/pedestrian/groundtruth/"
url_highway = "https://raw.githubusercontent.com/vision-agh/zaw_avs_materials/main/lab02_cfd/highway/groundtruth/"
url_office = "https://raw.githubusercontent.com/vision-agh/zaw_avs_materials/main/lab02_cfd/office/groundtruth/"

gt_pedestrian = load_ground_truth(url_pedestrian, "pedestrian")
gt_highway = load_ground_truth(url_highway, "highway")
gt_office = load_ground_truth(url_office, "office")

Loaded 1099 images
Loaded 1099 images
Loaded 1099 images


### Buffer methods

In [85]:
def buffer_method(img_width, img_height, img_list, buf_size, buf_func=np.median):
    buffer = np.zeros((img_height, img_width, buf_size)).astype("uint8")
    buffer_counter = 0
    buffer_full = False

    for img in img_list:
        buffer[:, :, buffer_counter] = img
        buffer_counter += 1
        if buffer_counter == buf_size:
            buffer_counter = 0
            buffer_full = True

        if buffer_full:
            result = buf_func(buffer, axis=2).astype("uint8")
            yield result



In [86]:

img_height, img_width = img_pedestrian[0].shape
a = buffer_method(img_width, img_height, img_pedestrian, 60)
print(next(a))
print()
print(next(a))

[[170 170 169 ... 221 217 216]
 [170 170 169 ... 233 232 232]
 [171 170 170 ... 244 247 249]
 ...
 [153 154 156 ... 183 182 182]
 [153 156 160 ... 182 182 182]
 [172 175 180 ... 184 185 185]]

[[170 170 169 ... 221 217 216]
 [170 170 169 ... 233 232 232]
 [171 170 170 ... 244 246 248]
 ...
 [153 154 156 ... 183 182 182]
 [153 155 160 ... 182 182 182]
 [172 175 180 ... 184 185 185]]
